# Generated by Django 5.2.9 on 2025-12-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Consultation')", max_length=100)),
                ('code', models.CharField(help_text="Unique code (e.g., 'consultation')", max_length=50, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee amount in Naira', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of this appointment type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time of appointment', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Appointment fee (auto-populated from appointment type)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor will be assigned after completing the session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type_new',
            field=models.ForeignKey(blank=True, help_text='Type of appointment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointmenttype'),
        ),
    ]
