# Generated by Django 5.2.9 on 2025-12-20 20:56

from django.db import migrations
from decimal import Decimal
from datetime import datetime


def populate_appointment_types(apps, schema_editor):
    """Create initial appointment types with default fees"""
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    
    appointment_types = [
        {
            'name': 'Consultation',
            'code': 'consultation',
            'fee': Decimal('5000.00'),
            'description': 'General consultation with a doctor',
            'is_active': True
        },
        {
            'name': 'Follow-up',
            'code': 'follow_up',
            'fee': Decimal('3000.00'),
            'description': 'Follow-up visit for existing patients',
            'is_active': True
        },
        {
            'name': 'Emergency',
            'code': 'emergency',
            'fee': Decimal('10000.00'),
            'description': 'Emergency medical consultation',
            'is_active': True
        },
        {
            'name': 'Check-up',
            'code': 'checkup',
            'fee': Decimal('4000.00'),
            'description': 'Routine health check-up',
            'is_active': True
        },
        {
            'name': 'Procedure',
            'code': 'procedure',
            'fee': Decimal('15000.00'),
            'description': 'Medical procedure or treatment',
            'is_active': True
        },
    ]
    
    for apt_type_data in appointment_types:
        AppointmentType.objects.create(**apt_type_data)


def migrate_existing_appointments(apps, schema_editor):
    """Migrate existing appointments to use new fields"""
    from django.utils import timezone as tz
    Appointment = apps.get_model('appointments', 'Appointment')
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    
    # Create a mapping from old type codes to new AppointmentType objects
    type_mapping = {
        'consultation': AppointmentType.objects.get(code='consultation'),
        'follow_up': AppointmentType.objects.get(code='follow_up'),
        'emergency': AppointmentType.objects.get(code='emergency'),
        'checkup': AppointmentType.objects.get(code='checkup'),
        'procedure': AppointmentType.objects.get(code='procedure'),
    }
    
    # Update all existing appointments
    for appointment in Appointment.objects.all():
        # Map old appointment_type to new appointment_type_new
        if appointment.appointment_type in type_mapping:
            appointment.appointment_type_new = type_mapping[appointment.appointment_type]
            appointment.fee = appointment.appointment_type_new.fee
        
        # Combine date and time into datetime field (timezone-aware)
        if appointment.appointment_date and appointment.appointment_time:
            naive_datetime = datetime.combine(
                appointment.appointment_date,
                appointment.appointment_time
            )
            # Make it timezone-aware
            appointment.appointment_datetime = tz.make_aware(naive_datetime)
        
        appointment.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration if needed"""
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    AppointmentType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmenttype_appointment_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_appointment_types, reverse_migration),
        migrations.RunPython(migrate_existing_appointments, migrations.RunPython.noop),
    ]
