# Generated by Django 5.2.9 on 2025-12-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_populate_appointment_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before', models.IntegerField(default=24, help_text='Hours before appointment to send reminder (e.g., 24 means remind 1 day before)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable all reminders')),
                ('send_email', models.BooleanField(default=True, help_text='Send email reminders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reminder Settings',
                'db_table': 'reminder_settings',
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(help_text='When the reminder should be sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reminder_type', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_reminders',
                'ordering': ['reminder_time'],
                'indexes': [models.Index(fields=['status', 'reminder_time'], name='appointment_status_5d8a32_idx')],
            },
        ),
    ]
