# Generated by Django 5.2.9 on 2025-12-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remindersettings_appointmentreminder'),
        ('patients', '0003_patient_country_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.OneToOneField(blank=True, help_text='Patient visit record created when consultation starts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='patients.patientvisit'),
        ),
    ]
