# Generated by Django 5.2.9 on 2025-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lga',
            field=models.CharField(choices=[('Demsa', 'Demsa'), ('Fufore', 'Fufore'), ('Ganye', 'Ganye'), ('Gayuk', 'Gayuk'), ('Gombi', 'Gombi'), ('Grie', 'Grie'), ('Hong', 'Hong'), ('Jada', 'Jada'), ('Lamurde', 'Lamurde'), ('Madagali', 'Madagali'), ('Maiha', 'Maiha'), ('Mayo-Belwa', 'Mayo-Belwa'), ('Michika', 'Michika'), ('Mubi North', 'Mubi North'), ('Mubi South', 'Mubi South'), ('Numan', 'Numan'), ('Shelleng', 'Shelleng'), ('Song', 'Song'), ('Toungo', 'Toungo'), ('Yola North', 'Yola North'), ('Yola South', 'Yola South')], default='Yola North', max_length=100, verbose_name='LGA'),
        ),
    ]
