# Generated by Django 5.2.9 on 2025-12-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_lga'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(choices=[('Cameroon', 'Cameroon'), ('Senegal', 'Senegal'), ('Gabon', 'Gabon'), ('Nigeria', 'Nigeria'), ('Niger', 'Niger'), ('Ghana', 'Ghana')], default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lga',
            field=models.CharField(blank=True, choices=[('Demsa', 'Demsa'), ('Fufore', 'Fufore'), ('Ganye', 'Ganye'), ('Gayuk', 'Gayuk'), ('Gombi', 'Gombi'), ('Grie', 'Grie'), ('Hong', 'Hong'), ('Jada', 'Jada'), ('Lamurde', 'Lamurde'), ('Madagali', 'Madagali'), ('Maiha', 'Maiha'), ('Mayo-Belwa', 'Mayo-Belwa'), ('Michika', 'Michika'), ('Mubi North', 'Mubi North'), ('Mubi South', 'Mubi South'), ('Numan', 'Numan'), ('Shelleng', 'Shelleng'), ('Song', 'Song'), ('Toungo', 'Toungo'), ('Yola North', 'Yola North'), ('Yola South', 'Yola South')], help_text='Local Government Area (Nigeria only)', max_length=100, verbose_name='LGA'),
        ),
    ]
