# Generated by Django 5.2.9 on 2025-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_country_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP in mmHg (e.g., 80)', null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP in mmHg (e.g., 120)', null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text="Doctor's clinical assessment, differential diagnosis, and plan"),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='examination_findings',
            field=models.TextField(blank=True, help_text='Physical examination findings (inspection, palpation, percussion, auscultation)'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm (e.g., 175.0)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, help_text='SpO2 percentage (e.g., 98)', null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='past_medical_history',
            field=models.TextField(blank=True, help_text='Relevant past medical history for this visit'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='presenting_complaint',
            field=models.TextField(blank=True, help_text='Detailed history of presenting illness'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Heart rate in beats per minute (e.g., 72)', null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Breaths per minute (e.g., 16)', null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C (e.g., 37.5)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (e.g., 70.5)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='notes',
            field=models.TextField(blank=True, help_text='Legacy general notes field'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='reason',
            field=models.TextField(help_text='Chief complaint/reason for visit'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='vital_signs',
            field=models.JSONField(blank=True, help_text='Legacy vital signs storage', null=True),
        ),
    ]
