# Generated by Django 5.2.9 on 2025-12-25 14:12

import accounting.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_migrate_invoice_statuses'),
        ('patients', '0004_add_clinical_documentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_transfer_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Cash Summaries',
                'db_table': 'accounting_daily_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(default=accounting.models.generate_expense_id, editable=False, max_length=20, unique=True)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('SALARIES', 'Staff Salaries'), ('UTILITIES', 'Utilities (Electricity, Water, etc.)'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('MAINTENANCE', 'Maintenance & Repairs'), ('RENT', 'Rent'), ('INSURANCE', 'Insurance'), ('LICENSES', 'Licenses & Permits'), ('MARKETING', 'Marketing & Advertising'), ('TRANSPORT', 'Transport & Fuel'), ('FOOD', 'Food & Refreshments'), ('EQUIPMENT', 'Equipment Purchase'), ('TRAINING', 'Staff Training'), ('COMMUNICATION', 'Phone & Internet'), ('OTHER', 'Other Expenses')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile Money'), ('DEBIT_CARD', 'Debit Card')], max_length=20)),
                ('description', models.TextField()),
                ('vendor', models.CharField(blank=True, help_text='Supplier/Vendor name', max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['expense_date'], name='accounting__expense_8c56d8_idx'), models.Index(fields=['category'], name='accounting__categor_5c7810_idx'), models.Index(fields=['is_approved'], name='accounting__is_appr_f92a57_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=accounting.models.generate_payment_id, editable=False, max_length=20, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS/Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('payment_type', models.CharField(choices=[('INVOICE', 'Invoice Payment'), ('CONSULTATION', 'Consultation Fee'), ('PHARMACY', 'Pharmacy Sale'), ('LAB_TEST', 'Lab Test'), ('PROCEDURE', 'Medical Procedure'), ('OTHER', 'Other Income')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, POS receipt number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_payments', to='billing.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_payments', to='patients.patient')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='accounting__payment_65fedb_idx'), models.Index(fields=['payment_method'], name='accounting__payment_dcd03f_idx'), models.Index(fields=['payment_type'], name='accounting__payment_2c8d8d_idx')],
            },
        ),
    ]
